conversion:
  messaging :
    video-status:
      url: ws://localhost:42308/video_status
    google :
      project-id: tp-ezipeflix-ss
      subscription-id: video-conversion-subscriber
  data :
    google :
      entity-name: video_conversion